### ISSUE TITLE
Php icon not working

### ISSUE THREAD

**Issue by ramiel** [vikjam/afterglow-theme#3]
Hi, I installed this fork in order to solve the problem that for me PHP icons are not shown:
![no_php](https://cloud.githubusercontent.com/assets/324687/13202471/7aa03e54-d89c-11e5-855b-5734e8c1f53a.png)
All the suggestion you gave in the issue regarding the R icon did not solve the problem. Any hint?

**Comment by vikjam** [comment]
Hmm, these icon preferences seem to be fidgety. Here's what I'm seeing:

![php_screen_02212016](https://cloud.githubusercontent.com/assets/1154799/13203121/6632730c-d87d-11e5-9908-feccf4ac32e6.png)

Can you double check that you have the syntax set to PHP? In the bottom right corner, it should say PHP.

![screen shot 2016-02-21 at 9 28 55 am](https://cloud.githubusercontent.com/assets/1154799/13203126/9b1e75e8-d87d-11e5-9a42-9945e08685ef.png)

You can set the preference to always open PHP files as PHP by opening a .php file and going to View > Syntax > Open all with current extension as...

Note that you maybe need to reload the folder/project for the icon to change. If that doesn't work, I'll dig into this!

**Comment by ramiel** [comment]
I had already checked this: the syntax is already to PHP and there is only the original PHP syntax from sublime (no plugins). There something else I can do to help you?

**Comment by ramiel** [comment]
I created an empty folder with one file only inside called "test.php", same behavior

**Comment by vikjam** [comment]
Alas. I'm sorry this is not working! Hmm, I don't really have bright ideas at the moment (I'm a bit busy with other things), but I'll definitely come back to this later in the week!

**Comment by vikjam** [comment]
Also, I took a quick look at other themes with users reporting similar issues. For example,
https://github.com/equinusocio/material-theme/issues/71
The users in that thread tried a variety things, but I don't think anyone seemed to have much of a solution. When I have some time, I'm going to try to understand more carefully how sidebar icons actually work in Sublime.

**Comment by ramiel** [comment]
Ok, I'll investigate on this as well and if I'll discover something I'll come back to you.

**Comment by mbicknese** [comment]
Just want to say I've got the exact same issue. Forcing syntax and creating new PHP files does not change the behaviour.

**Comment by vikjam** [comment]
Hmm, this is pretty weird. I see the proper icon as the screenshot earlier in this thread shows, but when I clear out my Sublime settings and reinstall the theme fresh, it doesn't show the PHP icon (only the gear). I'm still trying to trace down this issue. If either of you discover anything, please let me know!

By the way, could you report the Sublime build you're using? I think this issue from the Soda Theme might be helpful: https://github.com/buymeasoda/soda-theme/issues/202

**Comment by ramiel** [comment]
I use the build 3103.
By the way as said in [soda-theme/issues/202#issuecomment-187294985](https://github.com/buymeasoda/soda-theme/issues/202#issuecomment-187294985) the fix does not apply on this new version of sublime because the syntax file is in YAML

**Comment by vikjam** [comment]
I haven't forgotten about this! Unfortunately, I don't have a solution yet, but I've been noticing other themes experiencing similar issues: https://github.com/lefoy/cyanide-theme/issues/39

**Comment by vikjam** [comment]
I think I finally found the solution (https://github.com/sublimehq/Packages/issues/24). I'll change the preference file and push an update! Sorry it took so long!

**Comment by vikjam** [comment]
Updated! I think we should be good on PHP now.

![php](https://cloud.githubusercontent.com/assets/1154799/13624002/a4ec641a-e578-11e5-825a-fd6233b6b139.png)

**Comment by piotrgolawski** [comment]
Hey! Is there a solution?

Remove and install - nothing changed.

**Comment by vikjam** [comment]
Oh no! I really thought that fixed it! Just so that we're on the same page, did you manually install the fork? That is, you cloned the fork into your sublime packages:

```
git clone https://github.com/vikjam/afterglow-theme/ "Theme - Afterglow"
```

Note that the README still has the instructions from @YabataDesign, not this fork. The patch I pushed was simply to add "embedding.php" to the [icon preference file for PHP](https://github.com/vikjam/afterglow-theme/blob/master/Prefs/icon_php.tmPreferences).

If that's not your problem, I'll continue to leave this issue open as we hunt for solution.

**Comment by piotrgolawski** [comment]
Now I'm doing it manually as you said and IT WORKS!
Could you add your solution to Package Control?

Many thanks, that thing was annoying.

BTW. How to make left menu more visible?

**Comment by ramiel** [comment]
Great! This works for me too!
